### ISSUE TITLE
FATAL EXCEPTION

### ISSUE THREAD

**Issue by ikromy** [giantss/com.giants.multiimagespicker#1]
Hi,

I try this plugin in ionic framework and got error :

```
[ 09-21 01:43:09.069  1015: 2171 I/ActivityManager ]
START u0 {cmp=com.mggsoftware.mobile.asikdev/com.chinabike.plugins.mip.activity.LocalAlbum (has extras)} from uid 10094 on display 0

[ 09-21 01:43:09.085  5165: 5165 D/AndroidRuntime ]
Shutting down VM


[ 09-21 01:43:09.086  5165: 5165 E/AndroidRuntime ]
FATAL EXCEPTION: main
Process: com.mggsoftware.mobile.asikdev, PID: 5165
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.mggsoftware.mobile.asikdev/com.chinabike.plugins.mip.activity.LocalAlbum}: java.lang.ClassCastException: android.app.Application cannot be cast to com.chinabike.plugins.mip.AppContext
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
    at android.app.ActivityThread.-wrap11(ActivityThread.java)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:148)
    at android.app.ActivityThread.main(ActivityThread.java:5422)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
    at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
Caused by: java.lang.ClassCastException: android.app.Application cannot be cast to com.chinabike.plugins.mip.AppContext
    at com.chinabike.plugins.mip.activity.LocalAlbum.onCreate(LocalAlbum.java:58)
    at android.app.Activity.performCreate(Activity.java:6251)
    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
    ... 10 more

```

Android 6.0.1 , Nexus 6

Thanks

**Comment by giantss** [comment]
In AndroidManifest.xml application tag inside with `android: name = "com.chinabike.plugins.mip.AppContext"` try again。
